kind: pipeline
name: inc

steps:
- name: jdk8
  image: openjdk:8-jdk
  commands:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.3.6/0.3.6 && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - mill _.test

- name: jdk11
  image: openjdk:11-jdk
  commands:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.3.6/0.3.6 && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - mill _.test
