language: scala
sudo: required
dist: trusty

jdk:
  - openjdk8
  - openjdk11

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.3.5/0.3.5 && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
  - mill _.test

cache:
  directories:
  - $HOME/.coursier
