@startuml
title inc compiler - Dynamic

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  PackageBorderColor<<group>> #cccccc
  PackageFontColor<<group>> #cccccc
}
hide stereotype
top to bottom direction

skinparam rectangle<<8>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
}
skinparam rectangle<<9>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
}
skinparam rectangle<<5>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
}
skinparam rectangle<<6>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
}
skinparam rectangle<<7>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
}
skinparam person<<1>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}

person "==User\n<size:10>[Person]</size>" <<1>> as 1

package "inc compiler\n[Container]" <<3>> {
  skinparam PackageBorderColor<<3>> #444444
  skinparam PackageFontColor<<3>> #444444

  rectangle "==/parser\n<size:10>[Component]</size>\n\nParses a textual module into a syntax tree." <<5>> as 5
  rectangle "==/resolver\n<size:10>[Component]</size>\n\nResolves fully qualified names for each identifier in the syntax trees." <<6>> as 6
  rectangle "==/typechecker\n<size:10>[Component]</size>\n\nInfers types for every declaration and expression in the syntax tree." <<7>> as 7
  rectangle "==/codegen\n<size:10>[Component]</size>\n\nGenerates JVM bytecode from syntax trees. Embeds a binary syntax tree as a class file attribute." <<8>> as 8
  rectangle "==/main\n<size:10>[Component]</size>\n\nOrchestrates compilation using the other modules. Fetches imported modules from the classpath." <<9>> as 9
}

1 .[#707070,thickness=2].> 9 : "1. Source files"
9 .[#707070,thickness=2].> 5 : "2. Source text"
5 .[#707070,thickness=2].> 6 : "3. Parsed syntax trees"
6 .[#707070,thickness=2].> 7 : "4. Resolved syntax trees"
7 .[#707070,thickness=2].> 8 : "5. Typechecked syntax trees"
9 <.[#707070,thickness=2]. 8 : "6. Compiled classfiles"
@enduml