name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 17]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.coursier/cache/v1
          ~/.cache/coursier/v1
          ~/Library/Caches/Coursier/v1
          ~/AppData/Local/Coursier/Cache/v1
        key: ${{ runner.os }}-mill-coursier-cache-${{ hashFiles('build.sc') }}

    - name: Run tests
      run: |
        chmod +x ./mill
        ./mill _.test
        ./mill _.scoverage.xmlReport
        ./mill scoverage.xmlReportAll

    - name: Upload coverage reports
      uses: codecov/codecov-action@v1
      env:
        JAVA_VERSION: ${{ matrix.java-version }}
      with:
        file: ./out/scoverage/xmlReportAll.dest/scoverage.xml
        env_vars: JAVA_VERSION
