name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Run tests
      run: |
        chmod +x ./mill
        ./mill _.test
        ./mill _.scoverage.xmlReport
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v1
      env:
        JAVA_VERSION: ${{ matrix.java-version }}
      with:
        file: ./out/*/scoverage/xmlReport/dest/scoverage.xml
        env_vars: JAVA_VERSION
